### ISSUE TITLE
Fikse diverse bugs

### ISSUE THREAD

**Issue by larsore** [kartverket/backstage-plugin-risk-scorecard-frontend#372]
```[tasklist]
### Tasks
- [x] Fiks inifinite loop re-render
- [x] Fiks feil tidsberegning siden PR ble opprettet
- [x] Fiks index-feil
- [x] Fikse feil dersom man bytter mellom RoS'er med samme navn
```
